development:
  adapter: mysql
  encoding: utf8
  database: collabbit_dev
  username: collabbit
  password: Sahana123
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: collabbit_test
  username: collabbit
  password: Sahana123
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: collabbit_prod
  username: collabbit
  password: Sahana123
  host: localhost
