development:
    adapter: sqlite3
    database: db/development.sqlite3
    pool: 5
    timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  database: collabbit_test
  username: collabbit
  password: Sahana123
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: collabbit_prod
  username: collabbit
  password: Sahana123
  host: localhost
