development:
  adapter: mysql
  encoding: utf8
  database: 
  username: 
  password: 
  host: 

test:
  adapter: mysql
  encoding: utf8
  database: 
  username: 
  password: 
  host: 

production:
  adapter: mysql
  encoding: utf8
  database: 
  username: 
  password: 
  host: 
